# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd727a2d68334f08cafcccc97f00fb2993594862ec1b8aec95174b607420d0cc12a0958843839690c94109bcfabe5b6e287bbc70a8ff6da2b9a2762c3b19ba00

test:
  secret_key_base: 987a490db290d8dc3dfbdfff5e3f399fbd7209663d57dd64473c31ae0bdfb39cba88ee331a4eba574a1a064448e2b34e9d6389b34216d80c59feeb76f8de4e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
